mandatory_tags:
  - canonical_name: CreatedBy
    defined_tag_namespace: Operations
    defined_tag_key: CreatedBy
    aliases:
      - CreatedBy
      - Oracle-Tags.CreatedBy
      - created_by
      - createdby
      - creator
  - canonical_name: Owner
    defined_tag_namespace: Operations
    defined_tag_key: Owner
    aliases:
      - owner
      - resource_owner
      - owned_by
